# -*- coding: utf-8 -*-
{
    'name': "E-Office",
    'summary': "E-Office Management System",
    'description': """
    """,
    'author': "Bambang Bagus Candra(bambangbaguscandra@gmail.com),Nendi Apandi(nendi_apandi@yahoo.com) ",
    'website': "",
    'support': '',
    'category': 'E-Office',
    'version': '1.0',
    'depends': ['account','document', 'mail','hr','ir_sequence_autoreset','pelita_crew','muk_dms','document_attachment_manage','project','board'],
    'data': [
        'views/action.xml',
        'wizard/wizard_create_dispo_view.xml',
        'wizard/wizard_refuse_sk_view.xml',
        'wizard/wizard_create_memo_view.xml',
        'wizard/wizard_savedms_view.xml',
        'wizard/wizard_forward_dispo_view.xml',
        'wizard/donedispo_view.xml',
        'views/surat_masuk_view.xml',
        'views/disposisi_masuk.xml',
        'views/setting_view.xml',
        'views/nota_view.xml',
        'views/memorandum_view.xml',
        'views/surat_keluar_view.xml',
        'views/tanda_terima_view.xml',
        'views/delegasi_view.xml',
        'wizard/dashboard_report.xml',
        'views/view_report.xml',
        'security/eoffice_security.xml',
        'security/ir.model.access.csv',
        'report/report.xml',
        'report/report_surat_keluar.xml',
        'report/report_nota.xml',
        'report/report_memorandum.xml',
        'report/report_disposisi.xml',
        'report/report_disposisi_presdir.xml',
        'data/data.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}